- _committed-and-competent-staff/School Executive Committee.md
- _committed-and-competent-staff/Teaching Staff 2023.md
- _for-students-and-parents/Parent Volunteer (PV) Scheme.md
- _for-students-and-parents/Useful Links.md
1. change email address for Zhengyi inside EXCO
2. change the "thank you" as got extra ** inside
3. Change MiMS to MIMS
> Minor changes

- _committed-and-competent-staff/School Executive Committee.md
- _committed-and-competent-staff/Teaching Staff 2023.md
- _for-students-and-parents/Vendors.md
1. Delete name tag vendor + canteen vendor
2. Change insurance vendor to NTUC income
3.  update email of Song Zhenying both exco and FT page
> Update information 

- _committed-and-competent-staff/Teaching Staff 2023.md
Change Mdm He Hai Yang to Mr He Hai Yang
> Update file: Teaching Staff 2023.md

- _for-students-and-parents/Parent Volunteer (PV) Scheme.md
PV registration is closed. Need to update the changes.
Thank you
> Update file: Parent Volunteer (PV) Scheme.md

- _config.yml
- index.md
Change from Holy Innocent's Primary School to Holy Innocents' Primary School.
> Change for school name

- _hips-family/General School Information.md
Sorry for the request. the image link was not right. 
I had edit it to the correct link.
Thanks
> Replace of image link

- _committed-and-competent-staff/Teaching Staff 2023.md
- _hips-family/Contact Us.md
- pages/Announcements.md
- update the email address for Geyle Ho
- Update announcement
- Update the contact us page
> Change email, announcement and contact us page

- _committed-and-competent-staff/Teaching Staff 2023.md
Noted missing items.
Please allow changes
> Edit email address of FTs

- _committed-and-competent-staff/Teaching Staff 2023.md
Update from Yan Peng to Carolina.
Please approve
> 2C7 FT update

- _committed-and-competent-staff/School Executive Committee.md
- _committed-and-competent-staff/Teaching Staff 2023.md
I had removed Sabrina and Janis
> Remove staff from exco and teaching staff

- _committed-and-competent-staff/Teaching Staff 2023.md
Manage to resolve it. Please approve. Thanks
> Additional code appear

- _for-students-and-parents/School Bus Advertisement.md
- _for-students-and-parents/collection.yml
- _quality-cce-education/Awards & Achievements/CCA Achievements.md
Please approve for the bus advertisement.
AMs already checked and approved.
Thank You.
> Bus advertisement

- _committed-and-competent-staff/Teaching Staff 2023.md
Update of new email address of Shirley Long to shirley_long_a@moe.edu.sg
> Update of new email address for Shirley Long

- _for-students-and-parents/其他链接 Useful Links.md
There was a mistaken inside the useful link.
Updated. 
Please approave.
> Change of useful link 

- index.md
> Change of link inside website

- index.md
- pages/Announcements.md
Update Announcement tab and information.
> Update on Annoucement

- _committed-and-competent-staff/学校执行委员会 School Executive Committee.md
> SL name list 

- pages/Announcements.md
> Remove annoucement

- _for-students-and-parents/服务供应商 Vendors.md
Update on website link with vendors and bus information. Please approve. Thanks
> Update on vendor page

- _hips-family/校历 School Calendar.md
> School Calendar

- _quality-cce-education/性教育课程 Sexuality Education in School.md
Information was provided by Lily on the update
> Update on Sexuality Education page

- _for-students-and-parents/其他链接 Useful Links.md
- _for-students-and-parents/家长义工计划 Parent Volunteer (PV) Scheme.md
Change information for the application
> Parent Valunteer page update

- _hips-family/学校执行委员会 School Executive Committee.md
Change the covering info on website for WenFang
> Amendment for CL and SAP HOD

- _about-us/董事会 School Management Committee.md
- pages/Announcements.md
Update on new board members and remove some outdated annoucement.
> Update the SCM board and annoucement

- _about-us/学校信息 General School Information.md
- _hips-family/学校执行委员会 School Executive Committee.md
- _hips-family/教职人员 Teaching Staff.md
- _infohub/食堂广告 Canteen Advertisement.md
- pages/Announcements.md
Update list
1. remove some annoucement
2. update EXCO list
3. update FTs list
4. update on Canteen advertisement
5. update on general information
> Update done on 1 Jan 2025

- _hips-family/教职人员 Teaching Staff.md
- _infohub/家长义工计划 Parent Volunteer (PV) Scheme.md
- Update FT name for 2C8
- Update of Parent volunteer page
> Update for 3 Feb 2025

- _hips-experiences/QUALITY TEACHING & LEARNING/华文部门 Chinese Language Department.md
As per request by HOD CL and approved by HOD CL
> Update on 4 Feb

- _infohub/家长志工团队 Parent Support Group.md
Information provided by Mr Lau
> Update of PSG Exco list

- _about-us/校历 School Calendar.md
- _hips-family/教职人员 Teaching Staff.md
- pages/Announcements.md
1. Remove total Defence announcement
2. Remove PTM info from Calendar
3. Change email address of Joyce Chan
> Update on 25 Feb 2025

- _about-us/校历 School Calendar.md
- index.md
- pages/Announcements.md
1. update annoucement detail based on P letter
2. Calendar - public holiday info
3.  Front page info update for anniversary Mass (just add some line)
> Update for 11 March

- pages/40圣婴 40声音 40 Years 40 Stories.md
Update on the closing date of registration
> Update on 14 March 2025

- _about-us/校历 School Calendar.md
- _hips-family/执行与行政人员 Executive & Administrative Staff.md
- index.md
- pages/40圣婴 40声音 40 Years 40 Stories.md
- pages/Announcements.md
1. Update on announcement (PCTC)
2. Update new OM on the school EAS team
3. Update on public holiday info
> Update on 8 Apr 2025

- _about-us/办校策略重点 Strategic Thrusts.md
align the spacing as per request
> adjustment on School strategic thrusts

- pages/Announcements.md
Same content with PG that issue on 21 Apr 2025. For your approval.
> Update on HBL annoucement

- _about-us/校历 School Calendar.md
- pages/Announcements.md
Update inside announcement for
1. HBL 
2. Use your hand campaign
Update public holiday and date for report back to school
1. Vesak Day
2. Youth Day
> Update based on PG

- _about-us/校历 School Calendar.md
- _hips-family/教职人员 Teaching Staff.md
- pages/Announcements.md
Update co-FT for 2C8
removal of old info inside announcement and calendar page
> Update and removal of old info

- _hips-experiences/QUALITY CCE EDUCATION/性教育课程 Sexuality Education in School.md
> Update for S Ed

- _infohub/服务供应商 Vendors.md
Update information was given by Raimi for the bookshop vendor. 
For your approval
> Update on vendor address
